"use client";

import { useState } from "react";

type IconName = "spark" | "camera" | "voice" | "arrow" | "check" | "leaf" | "chart" | "users" | "plus" | "close" | "menu";

function Icon({ name, size = 20 }: { name: IconName; size?: number }) {
  const icons: Record<IconName, React.ReactNode> = {
    spark: <><path d="M12 2l1.45 5.05L18.5 8.5l-5.05 1.45L12 15l-1.45-5.05L5.5 8.5l5.05-1.45L12 2Z"/><path d="m19 15 .7 2.3L22 18l-2.3.7L19 21l-.7-2.3L16 18l2.3-.7L19 15Z"/></>,
    camera: <><path d="M4 7h3l1.4-2h7.2L17 7h3v12H4V7Z"/><circle cx="12" cy="13" r="4"/></>,
    voice: <><rect x="9" y="3" width="6" height="12" rx="3"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3M9 21h6"/></>,
    arrow: <><path d="M5 12h14M14 7l5 5-5 5"/></>,
    check: <path d="m5 12 4 4L19 6"/>,
    leaf: <><path d="M20 4C12 4 5 8 5 15c0 3 2 5 5 5 7 0 10-8 10-16Z"/><path d="M4 21c4-6 8-9 13-12"/></>,
    chart: <><path d="M4 19V5M4 19h16"/><path d="m7 15 4-5 3 2 5-7"/></>,
    users: <><circle cx="9" cy="8" r="3"/><circle cx="17" cy="10" r="2.5"/><path d="M3 20c.5-4 2.5-6 6-6s5.5 2 6 6M14 15c3.5-.5 6 1 7 4"/></>,
    plus: <path d="M12 5v14M5 12h14"/>, close: <path d="m6 6 12 12M18 6 6 18"/>, menu: <path d="M4 7h16M4 12h16M4 17h16"/>,
  };
  return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">{icons[name]}</svg>;
}

const dressings = [
  { name: "Оливковое масло", kcal: 548, fat: 24, note: "+ 74 ккал" },
  { name: "Йогурт", kcal: 486, fat: 15, note: "+ 12 ккал" },
  { name: "Без заправки", kcal: 474, fat: 13, note: "Базовая оценка" },
];

const dinners = [
  { name: "Тёплый боул с курицей", meta: "18 минут · 42 г белка", kcal: 624, cls: "dinner-one" },
  { name: "Лосось, овощи и киноа", meta: "25 минут · 39 г белка", kcal: 658, cls: "dinner-two" },
  { name: "Зелёный ролл с индейкой", meta: "Без готовки · 36 г белка", kcal: 582, cls: "dinner-three" },
];

const faqs = [
  ["Нужно ли взвешивать каждую порцию?", "Нет. JIVELO работает с фотографиями, привычными порциями и сохранёнными блюдами. Весы — дополнительный способ повысить точность, а не обязательное условие."],
  ["Насколько точно AI распознаёт еду?", "Точность зависит от блюда. Поэтому JIVELO показывает уверенность, диапазон порции и задаёт короткий вопрос, если масло, соус или способ приготовления заметно меняют результат."],
  ["Что будет, если я вышел за план?", "Ничего страшного. Сервис не предлагает голодать или отрабатывать еду. Он оценивает недельный тренд и помогает спокойно вернуться к обычному ритму."],
  ["Можно скрыть калории?", "Да. В спокойном режиме можно оставить фокус на регулярности, белке, клетчатке, воде, голоде и самочувствии."],
];

function Brand() {
  return <span className="brand"><span className="brand-mark"><i/><i/><i/></span><b>JIVELO</b></span>;
}

export default function Home() {
  const [menu, setMenu] = useState(false);
  const [modal, setModal] = useState(false);
  const [dressing, setDressing] = useState(0);
  const [dinner, setDinner] = useState(0);
  const [faq, setFaq] = useState(0);
  const [period, setPeriod] = useState("Сегодня");
  const meal = dinners[dinner];
  const sauce = dressings[dressing];

  return <main id="top">
    <header className="header">
      <a href="#top"><Brand/></a>
      <nav className={menu ? "nav open" : "nav"}>
        <a href="#camera">AI-камера</a><a href="#next">Что съесть</a><a href="#product">Продукт</a><a href="#pro">Для специалистов</a><a href="#pricing">Тарифы</a>
        <button className="mobile-cta" onClick={() => setModal(true)}>Начать бесплатно</button>
      </nav>
      <div className="header-actions"><button className="login" onClick={() => setModal(true)}>Войти</button><button className="button small" onClick={() => setModal(true)}>Начать бесплатно <Icon name="arrow" size={16}/></button><button className="menu" aria-label="Меню" onClick={() => setMenu(!menu)}><Icon name={menu ? "close" : "menu"}/></button></div>
    </header>

    <section className="hero shell">
      <div className="hero-copy"><div className="eyebrow"><Icon name="spark" size={15}/> AI-навигатор питания</div><h1>Не просто считайте.<br/><em>Знайте, что съесть дальше.</em></h1><p>JIVELO распознаёт еду по фото, честно показывает точность оценки, адаптируется к вашему прогрессу и превращает цифры в понятный следующий шаг.</p><div className="hero-actions"><button className="button large" onClick={() => setModal(true)}>Создать свой план <Icon name="arrow"/></button><a href="#camera" className="watch"><span><Icon name="camera" size={17}/></span> Посмотреть в действии</a></div><div className="trust"><span><Icon name="check" size={15}/>Без рекламы</span><span><Icon name="check" size={15}/>Без наказаний</span><span><Icon name="check" size={15}/>Данные под вашим контролем</span></div></div>
      <div className="hero-visual"><div className="hero-photo"><span className="scan"/><div className="tag salmon">Лосось <b>142 г</b></div><div className="tag grain">Киноа <b>128 г</b></div><div className="tag greens">Зелень <b>96 г</b></div><div className="ai-target">AI</div></div><div className="analysis glass"><div className="analysis-head"><span><Icon name="spark" size={16}/></span><div><small>Анализ готов</small><b>Обед распознан</b></div><i>Высокая точность</i></div><div className="macros"><span><b>612</b>ккал</span><span><b>42</b>белок</span><span><b>18</b>жиры</span><span><b>61</b>углеводы</span></div><div className="question"><small>Один вопрос улучшит оценку</small><b>Было масло при готовке?</b></div></div><div className="balance glass"><small>Осталось сегодня</small><strong>684 <i>ккал</i></strong><span><i/></span><p>Белок · ещё 38 г</p></div></div>
    </section>

    <section className="metrics"><div><b>10 сек</b><span>на запись еды</span></div><div><b>1–2</b><span>уточнения вместо анкеты</span></div><div><b>7 дней</b><span>в одном спокойном тренде</span></div><div><b>0</b><span>«проваленных» дней</span></div></section>

    <section className="camera shell" id="camera"><div className="section-title"><div className="eyebrow"><Icon name="camera" size={15}/> Честная AI-камера</div><h2>Один снимок —<br/><em>и вы уже знаете больше.</em></h2><p>Вы видите состав блюда, диапазон порции и только те вопросы, которые действительно влияют на результат.</p></div><div className="camera-demo"><div className="camera-image"><div className="corners"><i/><i/><i/><i/></div><span className="pin one">1</span><span className="pin two">2</span><span className="pin three">3</span><div className="vision"><span><Icon name="spark" size={14}/>JIVELO Vision</span><b>4 компонента</b></div></div><div className="camera-panel"><div className="panel-head"><div><small>ОБЕД · СЕГОДНЯ, 13:24</small><h3>Проверьте распознавание</h3></div><span>92%</span></div><div className="foods"><article><i>01</i><div><b>Лосось на гриле</b><small>142 г · высокая уверенность</small></div><strong>292 ккал</strong></article><article><i>02</i><div><b>Печёный картофель</b><small>184 г · средняя уверенность</small></div><strong>156 ккал</strong></article><article><i>03</i><div><b>Зелёный салат</b><small>116 г · высокая уверенность</small></div><strong>26 ккал</strong></article></div><div className="clarify"><span><Icon name="spark"/></span><div><small>Уточнение с наибольшим влиянием</small><b>Какая была заправка?</b></div><div className="options">{dressings.map((x,i)=><button className={dressing===i?"active":""} onClick={()=>setDressing(i)} key={x.name}>{x.name}<small>{x.note}</small></button>)}</div></div><div className="total"><div><small>ОБНОВЛЁННАЯ ОЦЕНКА</small><strong>{sauce.kcal} <i>ккал</i></strong></div><div><span>Белок 38 г</span><span>Жиры {sauce.fat} г</span><span>Клетчатка 8 г</span><i><b style={{width:`${70+dressing*7}%`}}/></i></div><button className="button" onClick={()=>setModal(true)}>Добавить в дневник <Icon name="arrow" size={16}/></button></div></div></div></section>

    <section className="difference shell" id="product"><div className="split-title"><div><div className="eyebrow"><Icon name="leaf" size={15}/> Другой принцип</div><h2>Большинство приложений<br/>показывают прошлое.</h2></div><div><h2><em>JIVELO помогает<br/>с будущим.</em></h2><p>Вместо ещё одной таблицы — интерфейс, который понимает контекст дня и предлагает конкретное действие.</p></div></div><div className="bento"><article className="dark"><span className="num">01</span><Icon name="camera"/><h3>Записать за 10 секунд</h3><p>Фото, голос, обычная фраза, штрихкод или повтор вчерашнего блюда.</p><div className="chips"><span><Icon name="camera" size={14}/>Фото</span><span><Icon name="voice" size={14}/>Голос</span><span>Aa Текст</span></div></article><article className="blue"><span className="num">02</span><Icon name="spark"/><h3>Понимать точность</h3><p>Источник данных, уверенность AI и возможность исправить порцию одним движением.</p><div className="levels"><span><i className="high"/>Высокая уверенность</span><span><i className="medium"/>Нужно уточнить</span><span><i className="source"/>Данные производителя</span></div></article><article className="coral"><span className="num">03</span><Icon name="arrow"/><h3>Выбрать следующий шаг</h3><p>Учитываем остаток дня, голод, время, бюджет и продукты дома.</p><div className="next-card"><small>ЛУЧШИЙ ВАРИАНТ СЕЙЧАС</small><b>Ужин с 40+ г белка</b><span>3 идеи · до 20 минут</span></div></article></div></section>

    <section className="next" id="next"><div className="shell next-inner"><div className="next-copy"><div className="eyebrow light"><Icon name="spark" size={15}/> Решение вместо отчёта</div><h2>Спросите не<br/>«сколько осталось?»,<br/><em>а «что мне подойдёт сейчас?»</em></h2><p>JIVELO соединяет дневной баланс с реальной жизнью: временем, продуктами дома, бюджетом и голодом.</p><div className="context"><span>15 минут</span><span>До 700 ккал</span><span>Дома</span><span>Много белка</span></div></div><div className="console"><div className="console-stats"><span><small>Осталось</small><b>680 <i>ккал</i></b></span><span><small>Белок</small><b>42 <i>г</i></b></span><span><small>Клетчатка</small><b>9 <i>г</i></b></span></div><div className={`dinner ${meal.cls}`}><span><Icon name="spark" size={14}/>Лучшее совпадение</span></div><div className="dinner-title"><div><small>JIVELO РЕКОМЕНДУЕТ</small><h3>{meal.name}</h3><p>{meal.meta}</p></div><strong>{meal.kcal}<i> ккал</i></strong></div><div className="why"><b>Почему подходит</b><p>Закрывает дефицит белка, остаётся в диапазоне и использует продукты из избранного.</p></div><div className="switch">{dinners.map((x,i)=><button className={dinner===i?"active":""} onClick={()=>setDinner(i)} key={x.name}>{i+1}</button>)}<button className="save" onClick={()=>setModal(true)}>Добавить в план <Icon name="arrow" size={15}/></button></div></div></div></section>

    <section className="adaptive shell"><div className="chart-card"><div className="chart-head"><div><small>ДИНАМИКА ЗА 8 НЕДЕЛЬ</small><h3>Ваше тело уточняет план</h3></div><span>− 2,8 кг</span></div><svg viewBox="0 0 640 260" aria-label="Плавный тренд веса"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2946c6" stopOpacity=".25"/><stop offset="1" stopColor="#2946c6" stopOpacity="0"/></linearGradient></defs><path className="grid" d="M30 45H610M30 105H610M30 165H610M30 225H610"/><path className="area" d="M30 65C90 77 110 100 165 103S240 136 290 142 360 171 415 183 515 205 610 218V250H30Z"/><path className="line" d="M30 65C90 77 110 100 165 103S240 136 290 142 360 171 415 183 515 205 610 218"/></svg><div className="adjust"><span><Icon name="spark"/></span><div><small>ЕЖЕНЕДЕЛЬНАЯ НАСТРОЙКА</small><b>Темп немного быстрее запланированного</b><p>Предлагаем добавить 120 ккал к обеду или перекусу.</p></div><button onClick={()=>setModal(true)}>Рассмотреть</button></div></div><div className="adaptive-copy"><div className="eyebrow"><Icon name="chart" size={15}/> Адаптивный план</div><h2>Формула даёт старт.<br/><em>Ваше тело уточняет план.</em></h2><p>JIVELO смотрит не на случайный день, а на связь между питанием, активностью, самочувствием и плавным трендом веса.</p><ul><li><Icon name="check" size={15}/>Небольшие, объяснимые корректировки</li><li><Icon name="check" size={15}/>Диапазоны вместо ложной точности</li><li><Icon name="check" size={15}/>Подтверждение перед изменением цели</li></ul></div></section>

    <section className="kind shell"><div className="kind-inner"><div><div className="eyebrow light"><Icon name="leaf" size={15}/> Интерфейс без стыда</div><h2>Ни одного<br/><em>«проваленного» дня.</em></h2><p>Питание — это тренд, а не экзамен. JIVELO не красит день в красный и не предлагает отрабатывать десерт.</p></div><article><span><Icon name="leaf"/></span><small>JIVELO · СЕГОДНЯ, 21:10</small><p>Сегодня получилось больше плана. Ничего компенсировать не нужно — завтра продолжим в обычном ритме.</p><button>Понятно</button></article></div></section>

    <section className="dashboard shell"><div className="dashboard-title"><div><div className="eyebrow"><Icon name="spark" size={15}/> Ваш день</div><h2>Важное видно<br/><em>с первого взгляда.</em></h2></div><p>Не сетка из десятков метрик, а спокойная картина дня: что уже получилось и какой следующий шаг будет самым полезным.</p></div><div className="app"><aside><Brand/><nav><button className="active">⌂ Сегодня</button><button>◫ Дневник</button><button>◇ План</button><button>⌁ Прогресс</button><button>⌘ Ассистент</button></nav><span>М</span></aside><div className="app-main"><div className="app-top"><div><small>СРЕДА, 18 ИЮНЯ</small><h3>Добрый день, Марина.</h3></div><div>{["Сегодня","Неделя","Месяц"].map(x=><button className={period===x?"active":""} onClick={()=>setPeriod(x)} key={x}>{x}</button>)}</div><button className="add" onClick={()=>setModal(true)}><Icon name="plus"/></button></div><div className="app-grid"><article className="rhythm"><small>ВАШ РИТМ СЕГОДНЯ</small><strong>Спокойный</strong><p>Вы держите устойчивый темп без жёстких ограничений.</p><span>78<small>%</small></span></article><article className="energy"><div><small>ЭНЕРГИЯ</small><strong>1 486 <i>из 2 050 ккал</i></strong><span><i/></span></div><div><b>76 г<small>белок</small></b><b>21 г<small>клетчатка</small></b><b>1,6 л<small>вода</small></b></div></article><article className="meals"><h4>Ваш день</h4><div><time>08:15</time><i className="yellow"/><span><b>Завтрак</b>Яйца, гречка, зелень</span><strong>468</strong></div><div><time>13:20</time><i className="green"/><span><b>Обед</b>Лосось, картофель, салат</span><strong>{sauce.kcal}</strong></div><div><time>19:00</time><i/><span><b>Ужин</b>{meal.name}</span><button>Запланирован</button></div></article><article className="action"><span><Icon name="spark"/></span><small>СЛЕДУЮЩИЙ ПОЛЕЗНЫЙ ШАГ</small><h4>Добавьте к ужину овощи или зелень</h4><p>Так вы закроете дневной фокус по клетчатке.</p><button onClick={()=>setModal(true)}>Подобрать вариант <Icon name="arrow" size={15}/></button></article></div></div></div></section>

    <section className="pro" id="pro"><div className="shell pro-inner"><div className="pro-copy"><div className="eyebrow light"><Icon name="users" size={15}/> JIVELO Pro</div><h2>Меньше таблиц.<br/><em>Больше времени на клиента.</em></h2><p>Специалист видит дневник, фотографии, тренды, самочувствие и точки, где действительно нужна поддержка.</p><button className="button light" onClick={()=>setModal(true)}>Узнать о JIVELO Pro <Icon name="arrow"/></button></div><div className="pro-screen"><div className="pro-head"><Brand/><span>18 июня · 12 клиентов</span></div><div className="pro-body"><aside><button className="active">Обзор</button><button>Клиенты</button><button>Сообщения</button><button>Отчёты</button></aside><div><div className="clients-head"><div><small>КЛИЕНТЫ, ТРЕБУЮЩИЕ ВНИМАНИЯ</small><h3>Добрый день, Анна.</h3></div><button>+ Пригласить</button></div><div className="clients"><article><i>АН</i><span><b>Алина Никитина</b><small>Последняя запись 2 часа назад</small></span><em className="stable">Стабильный ритм</em><strong>−0,4 кг</strong></article><article><i>ИМ</i><span><b>Ирина Мартынова</b><small>Повышенный вечерний голод</small></span><em>Посмотреть</em><strong>+12%</strong></article><article><i>ВС</i><span><b>Виктория С.</b><small>Недельный обзор готов</small></span><em className="stable">На плане</em><strong>84%</strong></article></div></div></div></div></div></section>

    <section className="pricing shell" id="pricing"><div className="pricing-title"><div><div className="eyebrow"><Icon name="spark" size={15}/> Простые тарифы</div><h2>Начните бесплатно.<br/><em>Подключайте интеллект, когда он нужен.</em></h2></div><p>Базовый дневник остаётся понятным. Premium открывает AI-распознавание, адаптивный план и персональные рекомендации.</p></div><div className="plans"><article><span>FREE</span><h3>Для знакомства</h3><p>Дневник питания и базовая динамика.</p><strong>0 ₽<small>/ навсегда</small></strong><ul><li><Icon name="check" size={14}/>Калории и БЖУ</li><li><Icon name="check" size={14}/>Тренд веса</li><li><Icon name="check" size={14}/>Ограниченные AI-снимки</li></ul><button className="button outline" onClick={()=>setModal(true)}>Начать бесплатно</button></article><article className="featured"><i>РЕКОМЕНДУЕМ</i><span>PREMIUM</span><h3>Для ежедневного ритма</h3><p>Полный AI-навигатор и адаптивный план.</p><strong>399 ₽<small>/ месяц при оплате за год</small></strong><ul><li><Icon name="check" size={14}/>Безлимитное фото и голос</li><li><Icon name="check" size={14}/>Что съесть сейчас?</li><li><Icon name="check" size={14}/>Адаптивные цели</li><li><Icon name="check" size={14}/>Расширенная аналитика</li></ul><button className="button light" onClick={()=>setModal(true)}>Попробовать Premium <Icon name="arrow" size={16}/></button></article><article><span>WITH PRO</span><h3>Со специалистом</h3><p>Общий план и профессиональная поддержка.</p><strong>По приглашению<small>специалиста или клиники</small></strong><ul><li><Icon name="check" size={14}/>Всё из Premium</li><li><Icon name="check" size={14}/>Общие цели</li><li><Icon name="check" size={14}/>Комментарии к приёмам пищи</li></ul><button className="button outline" onClick={()=>setModal(true)}>Для специалистов</button></article></div></section>

    <section className="faq shell"><div><div className="eyebrow"><Icon name="spark" size={15}/> Ответы без мелкого шрифта</div><h2>Частые вопросы</h2><p>О точности, калориях, данных и спокойном отношении к питанию.</p></div><div className="faq-list">{faqs.map(([q,a],i)=><article className={faq===i?"open":""} key={q}><button onClick={()=>setFaq(faq===i?-1:i)}><span>{String(i+1).padStart(2,"0")}</span><b>{q}</b><i>{faq===i?"−":"+"}</i></button><div><p>{a}</p></div></article>)}</div></section>

    <section className="final shell"><div><div><div className="eyebrow light"><Icon name="leaf" size={15}/> Начните с одного приёма пищи</div><h2>Питание становится проще,<br/><em>когда следующий шаг понятен.</em></h2><p>Присоединяйтесь к закрытому запуску JIVELO и помогите создать самый красивый и человечный сервис питания.</p><button className="button light large" onClick={()=>setModal(true)}>Получить ранний доступ <Icon name="arrow"/></button></div><div className="orbit"><span>AI</span><span>42 г</span><span>15 мин</span><div className="big-mark"><span/><span/><span/></div></div></div></section>

    <footer className="footer shell"><div><div><Brand/><p>Питание в ритме вашего тела.</p></div><div><b>Продукт</b><a href="#camera">AI-камера</a><a href="#next">Что съесть</a><a href="#pricing">Тарифы</a></div><div><b>Для бизнеса</b><a href="#pro">JIVELO Pro</a><a href="#pro">Для клиник</a></div><div><b>Компания</b><a href="#top">Методология</a><a href="#top">Безопасность</a></div></div><section><span>© JIVELO, 2026</span><a href="#top">Конфиденциальность</a><a href="#top">Условия</a><a href="#top">Наверх ↑</a></section></footer>

    {modal&&<div className="modal" onMouseDown={()=>setModal(false)}><div onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setModal(false)}><Icon name="close"/></button><span className="modal-icon"><Icon name="spark"/></span><div className="eyebrow">Закрытый запуск</div><h2>Попробуйте JIVELO<br/><em>раньше остальных.</em></h2><p>Оставьте email. Мы пригласим вас в первую группу и пришлём доступ к новому интерфейсу.</p><label><span>Email</span><input type="email" placeholder="name@example.com" autoFocus/></label><button className="button large" onClick={()=>setModal(false)}>Встать в лист ожидания <Icon name="arrow"/></button><small>Никакого спама. Только приглашение и важные обновления.</small></div></div>}
  </main>;
}
